
services:
  db: 
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=12345
      - POSTGRES_DB=next
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data: {}